services:
  grafana:
    user: root
    container_name: 'qmic-qmicdevices-panel'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: ${DEVELOPMENT:-false}
    # ports:
    #   - 3001:3000/tcp
    network_mode: 'host'
    volumes:
      - ./dist:/var/lib/grafana/plugins/qmic-qmicdevices-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/qmic-qmicdevices-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.qmic-qmicdevices-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: qmic-qmicdevices-panel
